### ISSUE TITLE
application.properties should not reside in data folder

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys/cakeshop#16]
#### Description of problem

Data folder regards live app persistence, while app.props is about config.

By conflating these two, it is difficult to configure docker containers in a reasonable way.

#### Expected behavior

A config file should be defined in the docker container via Dockerfile.

#### Actual behavior

Since the docker `volume` mounting option overwrites container volumes `after` dockerfile `COPY` commands, it overrides any config files that were expected in those volumes.

The rough workaround is to include config files on the host computer before deploying, but this destroys build repeatability. The Dockerfile should encompass any config, and so should be able to copy config files before volumes are mounted, without fear of being overwritten.

#### Steps to reproduce the behavior

Try dockerizing cakeshop with a custom application.properties file. Docker doesn't like it.

#### System information

Cakeshop version or commit hash: [version] `master`

Geth/Quorum version testing against: [run `geth version` or copy from Node Info in UI] /shrug

Cakeshop OS & Version: Windows/Linux/OSX OSX, deploying to an Ubuntu 16.04 box.

Browser OS & Version: Windows/Linux/OSX MSIE/Chrome/Firefox/Safari Chrome, not related.

**Comment by hermanjunge** [comment]
A perfect work around would be
 
* Scan for the file `application.properties.source`
* If you find it, `copy` it into `application.properties`
* Profit

Will bust if the user mounts both files, though

Do it here:

https://github.com/jpmorganchase/cakeshop/blob/master/docker/cakeshop/cakeshop.sh#L14
