### ISSUE TITLE
Feature Request: allow to send ETH to any ethereum address in Wallet window

### ISSUE THREAD

**Issue by jeffprestes** [ConsenSys/cakeshop#168]
#### Description of problem
Sometimes Devs would need to use Metamask to test or develop their Smart Contracts or DApps. So, would be useful and simple to Devs that at Cakeshop in Wallet window we had a text box at 'To' field allowing send ETH to any Ethereum valid account instead of a select box with only Ethereum accounts into Node keystore.

**Comment by bmcd** [comment]
Added in 0.12.0
