### ISSUE TITLE
Cannot unlock account nor deploy contract registry; Getting no meaningful error message.

### ISSUE THREAD

**Issue by Mereep** [ConsenSys/cakeshop#201]
#### Description of problem

- I am  running a local quorum istanbul-network
- I *can* connect to the network from within cakeshop
- I *cannot* unlock an existing Account
  - It  says "Sorry, could not unlock account. Please try again.". Not too helpful.
- I *cannot* deploy the Contract Registry
  - It just outputs *no* message at all, while doing just nothing. I suppose this happens due to not being able to unlock the accounts ?!
#### Expected behavior
- Get some meaningful error messages
- or just "work"

#### Steps to reproduce the behavior
- Spin up a istanbul network
- Add an account to one node
- Connect to node in Cakeshop
- Try unlocking an account

#### System information

Cakeshop version or commit hash: 0.11.0 (downloaded current readily build binary linked in readme)

Cakeshop runtime configuration: Don't know (connected to local network)

Geth/Quorum version testing against: 1.9.12-stable-9207bc7e(quorum-v21.1.0)

Cakeshop OS & Version:  OSX / Big Sur

Browser OS & Version: Opera

#### Backtrace/logs
I found this within the console logs, which I guess is the root cause of the problem: 

`[ERROR] 2021-02-11 16:44:35.117 [qtp1544147328-25] GethHttpServiceImpl - RPC request for {
  "jsonrpc" : "2.0",
  "method" : "personal_unlockAccount",
  "params" : [ "0x726efafefc64f9070f88f7ef204176649775be6c", "~~~~" ],
  "id" : "0x42"
} failed with RPC request failed: account unlock with HTTP access is forbidden
`
```

**Comment by Mereep** [comment]
Also, even if the log message helped me finding the problem (running the node with `--allow-insecure-unlock` actually fixes the problem),  seeing the passwords happily spread into the log files makes me a bit unhappy ;)

**Comment by bmcd** [comment]
Good catch! The error log no longer includes parameters like these in 0.12.0. Thanks!
